[package]
name = "aligned"
version = "0.1.1"
edition = "2021"
description = """
Safely transmute between raw byte slices and concrete data types.
"""
resolver = "2"
license = "MIT OR Apache-2.0"

[features]
default = ["derive"]
network-order = []
derive = ["aligned_derive"]

[dependencies]
byteorder = { version = "1.4.3", default-features = false }
log = "0.4.19"

[dependencies.aligned_derive]
path = "derive"
optional = true
