# Use appropriate Rust edition
edition = "2021"

# Wrap comments after max length of 85 characters
comment_width = 85
wrap_comments = true

# Make hexadecimal casing consistent
hex_literal_case = "Lower"

# Prevent Windows-style carriage returns
newline_style = "Unix"

# The "Default" setting has a heuristic which splits lines too aggresively.
use_small_heuristics = "Max"
struct_lit_width = 60
struct_variant_width = 60
single_line_if_else_max_width = 70

# Consistent imports ordering
imports_granularity = "Preserve"
group_imports = "StdExternalCrate"

# Reorder trait implementations for consistency.
reorder_impl_items = true
